In [1]:
!pip install numpy


In [19]:
# 1
import numpy as np

np.random.seed(80)
rand_array = np.random.randint(1, 100, (4, 4))
print(rand_array)

# a
display(rand_array[rand_array > 50]) 

# b
print(rand_array.sum(axis=0)) 
print(rand_array.sum(axis=1)) 

# c
#i
print(rand_array.max(axis=0)) 
print(rand_array.max(axis=1)) 
print()

# ii
print(rand_array.min(axis=0)) 
print(rand_array.min(axis=1))
print()

# iii
print(rand_array.mean(axis=0)) 
print(rand_array.mean(axis=1))


[[48 61 39 84]
 [11 51  4 87]
 [24 16 82  6]
 [65 10 93 43]]


array([61, 84, 51, 87, 82, 65, 93], dtype=int32)

[148 138 218 220]
[232 153 128 211]
[65 61 93 87]
[84 87 82 93]

[11 10  4  6]
[39  4  6 10]

[37.  34.5 54.5 55. ]
[58.   38.25 32.   52.75]


In [24]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: C:\Users\naama\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [27]:
import pandas as pd

In [42]:
# 2
new_games = {
"Final Fantasy VII Rebirth": 69.99,
"Astro Bot": 59.99,
"Star Wars Outlaws": 69.99,
"Silent Hill 2 Remake": 69.99,
"Elden Ring: Shadow of the Erdtree": 39.99,
"Dragon Age: The Veilguard": 69.99,
"Metaphor: ReFantazio": 59.99
}
pd_ser= pd.Series(new_games)
print(pd_ser)

#a
print(pd_ser["Metaphor: ReFantazio"])

# b
print(pd_ser.keys())

# c
print(pd_ser.iloc[3])  

# d
df=list(pd_ser.values)
print(df)
print(sum(df))

Final Fantasy VII Rebirth            69.99
Astro Bot                            59.99
Star Wars Outlaws                    69.99
Silent Hill 2 Remake                 69.99
Elden Ring: Shadow of the Erdtree    39.99
Dragon Age: The Veilguard            69.99
Metaphor: ReFantazio                 59.99
dtype: float64
59.99
Index(['Final Fantasy VII Rebirth', 'Astro Bot', 'Star Wars Outlaws',
       'Silent Hill 2 Remake', 'Elden Ring: Shadow of the Erdtree',
       'Dragon Age: The Veilguard', 'Metaphor: ReFantazio'],
      dtype='object')
69.99
[np.float64(69.99), np.float64(59.99), np.float64(69.99), np.float64(69.99), np.float64(39.99), np.float64(69.99), np.float64(59.99)]
439.93
